# Generated by Django 4.2.7 on 2023-11-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_mode', models.FloatField(blank=True, null=True)),
                ('duration_of_operation', models.FloatField(blank=True, null=True)),
                ('structural_risk', models.FloatField(blank=True, null=True)),
                ('functional_risk', models.FloatField(blank=True, null=True)),
                ('failure_probability', models.FloatField(blank=True, null=True)),
                ('damage', models.FloatField(blank=True, null=True)),
                ('system_condition_assessment', models.FloatField()),
                ('expert_assessment', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=20),
        ),
        migrations.CreateModel(
            name='OperatingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('output', models.CharField(choices=[('Non-Regular', 'Non-Regular'), ('Regular', 'Regular')], max_length=30, verbose_name='Operating Mode')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unit')),
            ],
        ),
        migrations.CreateModel(
            name='DurationOfOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('output', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unit')),
            ],
        ),
    ]
