# Generated by Django 4.2.7 on 2023-11-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rules_unit_cost_operatingmode_durationofoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='rule',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rules',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.unit'),
            preserve_default=False,
        ),
    ]
