# Generated by Django 4.2.7 on 2023-11-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rules_rule_rules_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
