# Generated by Django 4.2.7 on 2023-12-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_unit_alias_alter_rule_damage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='damage',
        ),
        migrations.DeleteModel(
            name='Damage',
        ),
    ]
