# Generated by Django 4.2.7 on 2023-12-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_rule_damage_remove_unit_damage_delete_damage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='structural_risk',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='structural_risk',
        ),
        migrations.DeleteModel(
            name='StructuralRisk',
        ),
    ]
